services:
  - type: web
    name: bot-zeus
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: DISCORD_TOKEN
        scope: all
