services:
  - type: web
    name: bot-zeus
    env: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        scope: all
