services:
  - type: worker
    name: bot-zeus
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_BOT_TOKEN
        scope: all
